### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by jimmckeeth** [HashLoad/boss#103]
Either installing the dependency, listing the dependencies, or updating the dependencies causes an out of memory error for [PythonEnvironments](https://github.com/embarcadero/pythonenviroments) project. 

Example, the command: 

`boss install https://github.com/embarcadero/pythonenviroments`

Produces the following:

```
[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency pythonenviroments
runtime: out of memory: cannot allocate 16777216-byte block (1694334976 in use)
fatal error: out of memory

goroutine 1 [running, locked to thread]:
runtime.throw({0x13aaa92, 0xd})
        /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/panic.go:1198 +0x64 fp=0x12451878 sp=0x12451864 pc=0xee45e4
runtime.(*mcache).allocLarge(0x1cd02d8, 0xc9a000, 0x0, 0x1)
        /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/mcache.go:229 +0x250 fp=0x124518ac sp=0x12451878 pc=0xec4320
runtime.mallocgc(0xc9a000, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/malloc.go:1088 +0x48b fp=0x124518fc sp=0x124518ac pc=0xebb4cb
runtime.growslice(0x1334180, {0x6fe70000, 0xa10000, 0xa14000}, 0xa18000)
        /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/slice.go:261 +0x3d7 fp=0x12451928 sp=0x124518fc pc=0xef83f7
gopkg.in/src-d/go-billy.v4/memfs.(*content).WriteAt(...)
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-billy.v4@v4.3.0/memfs/storage.go:183
gopkg.in/src-d/go-billy.v4/memfs.(*file).Write(0x127e6660, {0x1275c000, 0x8000, 0x8000})
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-billy.v4@v4.3.0/memfs/memory.go:267 +0x144 fp=0x1245196c sp=0x12451928 pc=0x126e964
gopkg.in/src-d/go-billy.v4/helper/chroot.(*file).Write(0x124052d0, {0x1275c000, 0x8000, 0x8000})
        <autogenerated>:1 +0x45 fp=0x1245198c sp=0x1245196c pc=0x11f1915
io.copyBuffer({0x34091990, 0x124052d0}, {0x3406ef28, 0x12906180}, {0x0, 0x0, 0x0})
        /opt/hostedtoolcache/go/1.17.9/x64/src/io/io.go:425 +0x224 fp=0x124519e0 sp=0x1245198c pc=0xf46d34
io.Copy(...)
        /opt/hostedtoolcache/go/1.17.9/x64/src/io/io.go:382
gopkg.in/src-d/go-git%2ev4.(*Worktree).checkoutFile(0x125ae2a0, 0x1291e720)
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.11.0/worktree.go:533 +0x240 fp=0x12451a4c sp=0x124519e0 pc=0x12696b0
gopkg.in/src-d/go-git%2ev4.(*Worktree).checkoutChangeRegularFile(0x125ae2a0, {0x1264e120, 0x27}, 0x1, 0x125904b0, 0x125cfa80, 0x125956e0)
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.11.0/worktree.go:499 +0xc0 fp=0x12451a90 sp=0x12451a4c pc=0x12693c0
gopkg.in/src-d/go-git%2ev4.(*Worktree).checkoutChange(0x125ae2a0, {{0x0, 0x0, 0x0}, {0x129a4a90, 0x2, 0x2}}, 0x125904b0, 0x125956e0)
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.11.0/worktree.go:394 +0x147 fp=0x12451ac4 sp=0x12451a90 pc=0x1268d77
gopkg.in/src-d/go-git%2ev4.(*Worktree).resetWorktree(0x125ae2a0, 0x125904b0)
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.11.0/worktree.go:359 +0x10f fp=0x12451b20 sp=0x12451ac4 pc=0x1268bef
gopkg.in/src-d/go-git%2ev4.(*Worktree).Reset(0x125ae2a0, 0x12899b93)
        /home/runner/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.11.0/worktree.go:292 +0x16b fp=0x12451b74 sp=0x12451b20 pc=0x126873b
github.com/hashload/boss/core/gitWrapper.UpdateCacheEmbedded({{0x124103f0, 0x30}, {0x13a6bf5, 0x6}, 0x0})
        /home/runner/work/boss/boss/core/gitWrapper/git_embedded.go:45 +0x123 fp=0x12451c1c sp=0x12451b74 pc=0x1271893
github.com/hashload/boss/core/gitWrapper.UpdateCache({{0x124103f0, 0x30}, {0x13a6bf5, 0x6}, 0x0})
        /home/runner/work/boss/boss/core/gitWrapper/git.go:25 +0x34 fp=0x12451c38 sp=0x12451c1c pc=0x1270804
github.com/hashload/boss/core/installer.GetDependency({{0x124103f0, 0x30}, {0x13a6bf5, 0x6}, 0x0})
        /home/runner/work/boss/boss/core/installer/vsc.go:28 +0x2b5 fp=0x12451ca0 sp=0x12451c38 pc=0x1275f75
github.com/hashload/boss/core/installer.makeCache({0x125ae240, 0x1, 0x1})
        /home/runner/work/boss/boss/core/installer/core.go:58 +0xcb fp=0x12451ce0 sp=0x12451ca0 pc=0x127366b
github.com/hashload/boss/core/installer.EnsureDependencies({{0x12587da0, 0x30}, {0x124d7ec0, 0x20}, {0x37eb6888, 0xeda3aecc4, 0x1743ac0}, 0x125942e0}, 0x12598280, 0x1)
        /home/runner/work/boss/boss/core/installer/core.go:46 +0x88 fp=0x12451d3c sp=0x12451ce0 pc=0x1273418
github.com/hashload/boss/core/installer.DoInstall(0x12598280, 0x1)
        /home/runner/work/boss/boss/core/installer/core.go:27 +0xce fp=0x12451e10 sp=0x12451d3c pc=0x12731de
github.com/hashload/boss/core/installer.LocalInstall({0x125a81b8, 0x1, 0x1}, 0x12598280, 0x1, 0x0)
        /home/runner/work/boss/boss/core/installer/local.go:11 +0x4e fp=0x12451e68 sp=0x12451e10 pc=0x127572e
github.com/hashload/boss/core.InstallModules({0x125a81b8, 0x1, 0x1}, 0x1, 0x0)
        /home/runner/work/boss/boss/core/installer.go:26 +0x1bb fp=0x12451ebc sp=0x12451e68 pc=0x12d454b
github.com/hashload/boss/cmd.glob..func3(0x1729580, {0x125a81b8, 0x1, 0x1})
        /home/runner/work/boss/boss/cmd/install.go:24 +0x41 fp=0x12451ed0 sp=0x12451ebc pc=0x12e9211
github.com/spf13/cobra.(*Command).execute(0x1729580, {0x125a8198, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x61c fp=0x12451f2c sp=0x12451ed0 pc=0x12b835c
github.com/spf13/cobra.(*Command).ExecuteC(0x1729800)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x343 fp=0x12451f98 sp=0x12451f2c pc=0x12b88b3
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/hashload/boss/cmd.Execute()
        /home/runner/work/boss/boss/cmd/root.go:38 +0x1ba fp=0x12451fc4 sp=0x12451f98 pc=0x12e8baa
main.main()
        /home/runner/work/boss/boss/app.go:8 +0x17 fp=0x12451fc8 sp=0x12451fc4 pc=0x12e9467
runtime.main()
        /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/proc.go:255 +0x23a fp=0x12451ff0 sp=0x12451fc8 pc=0xee6e0a
runtime.goexit()
        /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/asm_386.s:1319 +0x1 fp=0x12451ff4 sp=0x12451ff0 pc=0xf0f4e1
```

- Both PowerShell and CMD
- Deleted the cache and tried in a new project
- Closed and re-opened the terminal window
- Windows 11 Pro 22H2 with Windows Feature Experience Pack 1000.22632.1000.0
- 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz
- 32.0 GB (31.9 GB usable)
- Process Explorer reports it used 1.7 GB of RAM before the error (which matches the console output)

**Comment by jimmckeeth** [comment]
Reproduced in Windows 10 VM

Edition:	Windows 10 Pro
Version:	21H2
Installed on:	‎1/‎25/‎2022
OS build:	19044.1706
Experience:	Windows Feature Experience Pack 120.2212.4170.0

Processor:	11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz
Installed RAM:	4.00 GB (3.64 GB usable)
Product ID:	00330-80139-92576-AA619
System type:	64-bit operating system, x64-based processor
Pen and touch:	No pen or touch input is available for this display


```[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency pythonenviroments
[INFO ] Downloading dependency https://github.com/embarcadero/pythonenviroments
runtime: out of memory: cannot allocate 12582912-byte block (1723662336 in use)
```

**Comment by jimmckeeth** [comment]
Turns out I was running the 32-bit Windows version by accident. Switched to 64-bit and that fixed it for me. But the bug is still there for 32-bit versions.
